# Third-party services required to run the local Elements SDK runtime. Not deployed.
#
# Mongo only — the SDK's default local properties point at mongodb://localhost:27017/elements.
version: '3'
services:

  mongo:
    image: mongo:6.0.9
    command:
      - mongod
      - --replSet
      - local-test
    deploy:
      replicas: 1
    networks:
      - elements
    ports:
      - "27017:27017"

  rs-init:
    build:
      context: rs-init
    deploy:
      replicas: 1
    networks:
      - elements

networks:
  elements: